spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:postgresql://cohort5860-dashavl89-e8ae.h.aivencloud.com:27562/defaultdb
    username: avnadmin
    password: ${AIVEN_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGODB_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true